using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ProjectEuler.Problems
{
    /// <summary>
    /// Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
    /// By starting with 1 and 2, the first 10 terms will be:
    /// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
    /// 
    /// By considering the terms in the Fibonacci sequence whose values do not exceed four million,
    /// find the sum of the even-valued terms.
    /// </summary>
    /// <answer>
    /// 4613732
    /// </answer>
    public class _0002
    {
        public static int Run()
        {
            int previous = 1;
            int total = 2;

            for (int i = 2; i <= 4000000;)
            {
                if ((i + previous) % 2 == 0)
                {
                    total += i + previous;
                }

                int j = i + previous;
                previous = i;
                i = j;
            }

            return total;
        }
    }
}
