using System;
using ProjectEuler.Library;
using System.Linq;

namespace ProjectEuler.Problems
{
    /// <summary>
    /// The sequence of triangle numbers is generated by adding the natural numbers.
    /// So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
    /// 1, 3, 6, 10, 15, 21, 28, 36, 45, 55
    ///  
    /// What is the value of the first triangle number to have over five hundred divisors?
    /// </summary>
    /// <answer>
    /// 76576500
    /// </answer>
    class _0012
    {
        internal static int Run()
        {
            int result = 0;

            foreach (int x in TriangleNumber.GenerateNumbers())
            {        
                if (Arithmetic.GetDivisors(x).Count() > 500)
                {
                    result = x;
                    break;
                } 
            }

            System.Diagnostics.Debug.WriteLine(result);
            return result;
        }
    }
}
