using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ProjectEuler.Problems
{
    /// <summary>
    /// The sequence of triangle numbers is generated by adding the natural numbers.
    /// So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
    /// 1, 3, 6, 10, 15, 21, 28, 36, 45, 55
    ///  
    /// What is the value of the first triangle number to have over five hundred divisors?
    /// </summary>
    /// <answer>
    /// 76576500
    /// </answer>
    internal static class _0014
    {
        internal static void Run()
        {
            //BigInteger result = 0;

            //for (int i = 0; i < array.Length; i++)
            //{
            //    result += BigInteger.Parse(array[i]);
            //}

            //System.Diagnostics.Debug.WriteLine(result);
            //return result;
        }
    }
}
